import React from 'react';
import { AlertTriangle, ShieldCheck, ExternalLink } from 'lucide-react';

export const AdvisoryNote: React.FC = () => {
  return (
    <footer className="w-full mt-16 border-t border-slate-800/80 bg-slate-950/90 py-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto space-y-4">
        
        {/* Main Advisory Box */}
        <div className="p-4 sm:p-5 rounded-2xl bg-slate-900/80 border border-slate-800 flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
          <div className="flex items-start space-x-3.5">
            <div className="p-2.5 rounded-xl bg-amber-500/10 text-amber-400 border border-amber-500/20 shrink-0 mt-0.5 md:mt-0">
              <AlertTriangle className="w-5 h-5" />
            </div>
            <div className="space-y-1">
              <h4 className="text-xs font-bold text-amber-300 uppercase tracking-wider">
                Official Meteorological Advisory & Decision Support Disclaimer
              </h4>
              <p className="text-xs text-slate-300 leading-relaxed max-w-4xl">
                <strong>Cyclone Intelligence</strong> is an AI/ML-assisted decision support system for multi-spectral satellite pattern identification and storm intensity prediction. Predictions generated by this platform are model estimates and should <strong>never</strong> be used as a sole source for public evacuation or emergency warnings. Official tropical cyclone bulletins and warnings for the North Indian Ocean are issued exclusively by the <strong>India Meteorological Department (IMD)</strong>.
              </p>
            </div>
          </div>

          <a
            href="https://mausam.imd.gov.in"
            target="_blank"
            rel="noopener noreferrer"
            className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-cyan-300 hover:text-cyan-200 text-xs font-medium border border-slate-700 transition-colors flex items-center space-x-1.5 shrink-0"
          >
            <span>Visit IMD Mausam</span>
            <ExternalLink className="w-3.5 h-3.5" />
          </a>
        </div>

        {/* Footer Meta */}
        <div className="flex flex-col sm:flex-row items-center justify-between text-xs text-slate-400 border-t border-slate-900 pt-4 gap-2">
          <div className="flex items-center space-x-2">
            <ShieldCheck className="w-4 h-4 text-cyan-400" />
            <span className="font-mono text-[11px]">CYCLONE INTELLIGENCE • Multi-Spectral AI Satellite Processing Engine</span>
          </div>
          <div className="text-slate-400 font-mono text-[11px]">
            INSAT-3D TIR-1 & Water Vapour Analytics
          </div>
        </div>

      </div>
    </footer>
  );
};
